# Generated by Django 5.1.6 on 2025-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Cabo', 'Cabo'), ('Peça de Computador', 'Peça de Computador'), ('Outro', 'Outro')], max_length=20)),
                ('estoque_minimo', models.IntegerField()),
            ],
        ),
    ]
