# Generated by Django 5.1.6 on 2025-03-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_manutencao_itensmanutencao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensManutencao',
            new_name='ItemManutencao',
        ),
    ]
